```{r}
library(grid)
library(ggplot2)
data=read.table("data3.txt",header=TRUE)
dim(data)[1]
data$height=300-30*data$sample
# 数据处理
for ( i in 1:9)
  {
  data1=subset(data,sample==i)
  min=min(min(data1$start),min(data1$end))
  for(j in 1:dim(data)[1])
    {
    if (isTRUE(data$sample[j]==i))
      {
      data$start1[j]=data$start[j]-min+3000
      data$end1[j]=data$end[j]-min+3000
      }
    }
  }
max_all=max(data$start1,data$end1)

# 把空白片段删除，而不是把短片段扩增
data1=subset(data,sample1==1)
data1_1=data1[order(data1$start1),]
#data1_1$sample=8
data1_1$start1=data1_1$start1+10000

data2=subset(data,sample1==2)
data2_1=data2[order(data2$start1),]
add=max(data2_1$end1)
data2_1$start1=0-data2_1$start1+add+3000
data2_1$end1=0-data2_1$end1+add+3000

#Cap1
data3=subset(data,sample1==3)
data3_1=data3[order(data3$start1),]
for ( i in 1:5)
  {
  if (data3_1$start1[i]>2800000)
    {
    data3_1$start1[i]=data3_1$start1[i]-2800000
    data3_1$end1[i]=data3_1$end1[i]-2800000
    }
  }
add=max(data3_1$end1)
data3_1$start1=0-data3_1$start1+add+3000
data3_1$end1=0-data3_1$end1+add+3000
#Cap2
data4=subset(data,sample1==4)
data4_1=data4[order(data4$start1),]
for (i in 1:4)
  {
  if (data4_1$start1[i]>2000000)
    {
    data4_1$start1[i] = data4_1$start1[i]-2000000
    data4_1$end1[i] = data4_1$end1[i]-2000000
    }
  }
for (i in 1:4)
  {
  if (data4_1$start1[i]>400000)
    {
    data4_1$start1[i] = data4_1$start1[i]-100000
    data4_1$end1[i] = data4_1$end1[i]-100000
    }
  }
add=max(data4_1$end1)
data4_1$start1=0-data4_1$start1+add+3000
data4_1$end1=0-data4_1$end1+add+3000
# DMC
data5=subset(data,sample1==5)
data5_1=data5[order(data5$start1),]
for (i in 1:12)
  {
  if (data5_1$start1[i]>2430000)
    {
    data5_1$start1[i] = data5_1$start1[i]-2430000
    data5_1$end1[i] = data5_1$end1[i]-2430000
    }
  }
for (i in 1:12)
  {
  if (data5_1$start1[i]>140000)
    {
    data5_1$start1[i] = data5_1$start1[i]-140000
    data5_1$end1[i] = data5_1$end1[i]-140000
    }
  }
for (i in 1:12)
  {
  if (data5_1$start1[i]>300000)
    {
    data5_1$start1[i] = data5_1$start1[i]-330000
    data5_1$end1[i] = data5_1$end1[i]-330000
    }
  }
data5_1$start1[12]=data5_1$start1[12]+10000
data5_1$end1[12]=data5_1$end1[12]+10000

data6=subset(data,sample1==6)
data6=data6[order(data6$start1),]
data6$start1=0-data6$start1+max(data6$start1,data6$end1)
data6$end1=0-data6$end1+max(data6$start1,data6$end1)
data6_1=data6[order(data6$start1),]
data6_1$start1=10*data6_1$start1
data6_1$end1=10*data6_1$end1

data7=subset(data,sample1==7)
data7_1=data7[order(data7$start1),]
data7_1$start1=10*data7_1$start1
data7_1$end1=10*data7_1$end1

data8=subset(data,sample1==8)
data8_1=data8[order(data8$start1),]
  for (i in 1:2)
  {
  if (data8_1$start1[i]>300000)
    {
    data8_1$start1[i] = data8_1$start1[i]-10300000
    data8_1$end1[i] = data8_1$end1[i]-10300000
    }
  }
#add=max(data8_1$end1)
#data8_1$start1=0-data8_1$start1+add+3000
#data8_1$end1=0-data8_1$end1+add+3000

data9=subset(data,sample1==9)
data9_1=data9[order(data9$start1),]
  for (i in 1:2)
  {
  if (data9_1$start1[i]>300000)
    {
    data9_1$start1[i] = data9_1$start1[i]-5400000
    data9_1$end1[i] = data9_1$end1[i]-5400000
    }
  }
#add=max(data9_1$end1)
#data9_1$start1=0-data9_1$start1+add+3000
#data9_1$end1=0-data9_1$end1+add+3000

data_use=rbind(data1_1,data2_1,data3_1,data4_1,data5_1,data6_1,data7_1,data8_1,data9_1)
class(data6_1$start1)
#data_use$height=250-30*data_use$sample
data_use_1=subset(data_use,direct=="+")
data_use_1$start2=data_use_1$start1
data_use_1$end2=data_use_1$start1+2000
data_use_2=subset(data_use,direct=="-")
data_use_2$start2=data_use_2$end1
data_use_2$end2=data_use_2$end1-2000

data_use_3=rbind(data_use_1,data_use_2)
# 画线
class(data_use_3$X8)
?shape
m=ggplot(data_use_3,aes(start1,height))+geom_point(shape=17,size=2,colour=data_use_3$X8)+ylim(-10,300)+xlab("")+ylab("")+theme(axis.text.x=element_blank(),axis.text.y=element_blank(),panel.background=element_rect(colour=NA),plot.background=element_rect(colour=NA))+
  geom_segment(x=0,y=300-30*max(data1_1$sample),xend=max(data1_1$end1)+3000,yend=300-30*max(data1_1$sample),size=3,colour="grey")+
  geom_segment(x=0,y=300-30*max(data2_1$sample),xend=max(data2_1$end1)+3000,yend=300-30*max(data2_1$sample),size=3,colour="grey")+
  geom_segment(x=0,y=300-30*max(data3_1$sample),xend=max(data3_1$end1)+3000,yend=300-30*max(data3_1$sample),size=3,colour="grey")+
  geom_segment(x=0,y=300-30*max(data4_1$sample),xend=max(data4_1$end1)+3000,yend=300-30*max(data4_1$sample),size=3,colour="grey")+
  geom_segment(x=0,y=300-30*max(data5_1$sample),xend=max(data5_1$end1)+3000,yend=300-30*max(data5_1$sample),size=3,colour="grey")+
  geom_segment(x=0,y=300-30*max(data6_1$sample),xend=max(data6_1$end1)+3000,yend=300-30*max(data6_1$sample),size=3,colour="grey")+
  geom_segment(x=0,y=300-30*max(data7_1$sample),xend=max(data7_1$end1)+3000,yend=300-30*max(data7_1$sample),size=3,colour="grey")+   
  geom_segment(x=0,y=300-30*max(data8_1$sample),xend=max(data8_1$end1)+3000,yend=300-30*max(data8_1$sample),size=3,colour="grey")+
  geom_segment(x=0,y=300-30*max(data9_1$sample),xend=max(data9_1$end1)+3000,yend=300-30*max(data9_1$sample),size=3,colour="grey")+
  geom_segment(size=1,aes(x=data_use_3$start2,y=data_use_3$height,xend=data_use_3$end2,yend=data_use_3$height,colour=data_use_3$X8),arrow=arrow(type="closed",length=unit(0.2,"inches")))+
theme(legend.position=c(0.5,0.05),legend.background=element_blank())
#+guides(colour=guide_legend(title=NULL,nrow=1,label.position="bottom",size=3,keywidth=6,keyheight=2,label.hjust=0.5))
m
  n=m+geom_segment(size=1,aes(x=70000,y=5,xend=72000,yend=5,colour=factor(1)),arrow=arrow(type="closed",length=unit(0.2,"inches")))+
geom_segment(size=1,aes(x=150000,y=5,xend=152000,yend=5,colour=factor(2)),arrow=arrow(type="closed",length=unit(0.2,"inches")))+
geom_segment(size=1,aes(x=230000,y=5,xend=232000,yend=5,colour=factor(3)),arrow=arrow(type="closed",length=unit(0.2,"inches")))+
geom_segment(size=1,aes(x=310000,y=5,xend=312000,yend=5,colour=factor(4)),arrow=arrow(type="closed",length=unit(0.2,"inches")))+
geom_segment(size=1,aes(x=390000,y=5,xend=392000,yend=5,colour=factor(5)),arrow=arrow(type="closed",length=unit(0.2,"inches")))+
geom_segment(size=1,aes(x=480000,y=5,xend=482000,yend=5,colour=factor(6)),arrow=arrow(type="closed",length=unit(0.2,"inches")))+
geom_segment(size=1,aes(x=560000,y=5,xend=562000,yend=5,colour=factor("black")),arrow=arrow(type="closed",length=unit(0.2,"inches")))+
geom_text(x=70000,y=-6,label="Family1",adj=0.5,family="serif",fontface="italic",size=7)+
geom_text(x=150000,y=-6,label="Family2",adj=0.5,family="serif",fontface="italic",size=7)+
geom_text(x=230000,y=-6,label="Family3",adj=0.5,family="serif",fontface="italic",size=7)+
geom_text(x=310000,y=-6,label="Family4",adj=0.5,family="serif",fontface="italic",size=7)+
geom_text(x=390000,y=-6,label="Family5",adj=0.5,family="serif",fontface="italic",size=7)+
geom_text(x=480000,y=-6,label="Family6",adj=0.5,family="serif",fontface="italic",size=7)+
geom_text(x=560000,y=-6,label="Single gene clade",adj=0.5,family="serif",fontface="italic",size=7)

  #scale_colour_discrete(labels=c("Subfamily1","Subfamily2","Subfamily3","Subfamily4","Subfamily5","Subfamily6","N"))
  n1=n+scale_colour_manual(values=c("red","blue","yellow","green","cyan","darkorchid","black"),labels=c("Family1","Family2","Family3","Family4","Family5","Family6","Single gene clade"))+theme(legend.text=element_text(face="italic",size=15))

t=n1+geom_text(x=10000,y=70,label="S.lyc 08g",adj=0,family="serif",fontface="italic",size=7)+
  geom_text(x=10000,y=40,label="S.lyc 09g",adj=0,family="serif",fontface="italic",size=7)+
  geom_text(x=10000,y=280,label="CA 01g",adj=0,family="serif",fontface="italic",size=7)+
  geom_text(x=10000,y=250,label="Capang 01g",adj=0,family="serif",fontface="italic",size=7)+
  geom_text(x=10000,y=220,label="Capana 01g",adj=0,family="serif",fontface="italic",size=7)+
  geom_text(x=10000,y=190,label="DM unknow",adj=0,family="serif",fontface="italic",size=7)+
  geom_text(x=10000,y=160,label="DM 08g",adj=0,family="serif",fontface="italic",size=7)+
  geom_text(x=10000,y=130,label="SB(71) 08g",adj=0,family="serif",fontface="italic",size=7)+
  geom_text(x=10000,y=100,label="SB(70) 08g",adj=0,family="serif",fontface="italic",size=7)
t+theme(legend.text=element_text(size=17),panel.background=element_rect(fill="white",colour=NA),panel.grid.minor=element_blank(),panel.grid.major=element_blank(),axis.line=element_line(colour=NA),axis.ticks=element_blank(),legend.position="none")
#n +geom_segment(x=100000,y=163,xend=100000,yend=157,lwd=0.7)+
#  geom_segment(x=105000,y=163,xend=105000,yend=157,lwd=0.7)

```

```{r}
m=ggplot(data_use_3,aes(start1,height))+geom_point(shape=17,size=2,aes(colour=factor(data_use_3$X8)))+ylim(-10,205)+xlab("")+ylab("")+theme(axis.text.x=element_blank(),axis.text.y=element_blank())+
  geom_segment(x=0,y=250-30*max(data1_1$sample),xend=max(data1_1$end1)+3000,yend=250-30*max(data1_1$sample),size=3,colour="grey")+
  geom_segment(x=0,y=250-30*max(data2_1$sample),xend=max(data2_1$end1)+3000,yend=250-30*max(data2_1$sample),size=3,colour="grey")+
  geom_segment(x=0,y=250-30*max(data3_1$sample),xend=max(data3_1$end1)+3000,yend=250-30*max(data3_1$sample),size=3,colour="grey")+
  geom_segment(x=0,y=250-30*max(data4_1$sample),xend=max(data4_1$end1)+3000,yend=250-30*max(data4_1$sample),size=3,colour="grey")+
  geom_segment(x=0,y=250-30*max(data5_1$sample),xend=max(data5_1$end1)+3000,yend=250-30*max(data5_1$sample),size=3,colour="grey")+
  geom_segment(x=0,y=250-30*max(data6_1$sample),xend=max(data6_1$end1)+3000,yend=250-30*max(data6_1$sample),size=3,colour="grey")+
  geom_segment(x=0,y=250-30*max(data7_1$sample),xend=max(data7_1$end1)+3000,yend=250-30*max(data7_1$sample),size=3,colour="grey")+   
  geom_segment(size=1,aes(x=data_use_3$start2,y=data_use_3$height,xend=data_use_3$end2,yend=data_use_3$height,colour=factor(data_use_3$X8),arrow=arrow(type="closed",),size=5))+guides(colour=guide_legend(title=NULL,nrow=1,label.position="bottom",size=3,keywidth=4,keyheight=2,label.hjust=0.5))+theme(legend.position=c(0.5,0.05),legend.background=element_blank())+
  scale_colour_discrete(labels=c("Subfamily1","Subfamily2","Subfamily3","Subfamily4","Subfamily5","Subfamily6","N"))
?arrow
m
```